name: time_since
description: "A new Flutter project."
publish_to: "none"
version: 0.1.16+22

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  shared_preferences: ^2.0.0
  add_2_calendar: ^2.2.0
  password_strength: ^0.2.0
  lpinyin: ^2.0.2
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "branding/Gemini_Generated_Image_t7ux3xt7ux3xt7ux.png"
  min_sdk_android: 21 # set to min_sdk_version of your project
